env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-duplicate-imports:
    - error
    - includeExports: true
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '^_.*'
  sort-imports:
    - warn
    - allowSeparatedGroups: true
      memberSyntaxSortOrder:
        - none
        - all
        - single
        - multiple
  '@typescript-eslint/member-delimiter-style':
    - warn
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
overrides:
  - files:
    - 'src/**/*.spec.ts'
    - 'test/**'
    rules:
      '@typescript-eslint/no-empty-function':
        - error
        - allow:
          - methods